#Q5.Write a program for arithmetic opertators?
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
addition = num1 + num2
subtraction = num1 - num2
multiplication = num1 * num2
division = num1 / num2 
floor_division = num1 // num2  
modulus = num1 % num2  
exponentiation = num1 ** num2 
print(addition)
print(subtraction)
print(multiplication)
print(division)
print(floor_division)
print(modulus)
print(exponentiation)